### ISSUE TITLE
Api only returns last 10 transactions, limit and sortby functionality doesn't work.

### ISSUE THREAD

**Issue by anaamnizami** [dex-guru/dg-sdk-node#5]
`sdk
  .getTokenSwaps(
    ChainChoices._56,
    "0xc2098a8938119a52b1f7661893c0153a6cb116d5",
    1635794413,
    1638040819,
    null,
    null,
    null,
    null,
    100
  )
  .then((res) => console.log(res.data.length))
  .catch((err) => console.log(err));
`

**Comment by fmontserrat** [comment]
Thanks for reporting this @anaamnizami

Issue is resolved by https://github.com/dex-guru/dg-sdk-node/pull/7 and the fix will be included in `1.0.7`
